4,5주차_미션_웨이
UMC-6th-ERICA-Server-Spring/SERVER-A pull request #3
Opened 2024-05-07 08:08 UTC by thwldus

## Summary

- 4주차: 설계한 데이터베이스 이미지 파일 생성
- 5주차: 4주차에 설계한 데이터베이스 기반으로 쿼리문 작성 파일 생성

## Describe your code

- 4주차
 1. 사용자 테이블과 회원가입 시 선택하는 선호음식 테이블 연결
 2. 사용자 테이블과 부여되는 미션, 사용자가 작성하는 리뷰 테이블 연결
 3. 특정 가게가 생성하는 미션, 가게에 달리는 리뷰도 일대다관계로 연결 
- 5주차
워크북 미션에 주어진 요구사항을 위한 쿼리문 작성

## Checklist

- [ ] 리뷰어 등록

2024-05-07 09:40 UTC, msk226 reviewed
스터디 시간에 다 같이 확인하고 Approve 하겠습니다! 고생하셨어요~

2024-05-07 09:41 UTC, msk226 commented on 웨이/week5.sql
유저와 미션의 관계는 일대다 보다는 다대다 관계와 가깝지 않을까요?

2024-05-07 09:48 UTC, thwldus commented on 웨이/week5.sql
다대다가 적절하다고 생각했는데, ERD 라이브러리 상에서 다대다 연결선을 그리는 법을 찾지 못했습니다.
해당 부분은 스터디 시간에 질문 드리고 수정해보도록 하겠습니다!

2024-05-07 09:49 UTC, msk226 commented on 웨이/week5.sql
https://siyoon210.tistory.com/26 

위 링크 참고 하시면 도움 될 것 같아요!

2024-05-08 14:14 UTC, thwldus commented
사용자와 미션 테이블을 바로 연결시키지 않고 할당미션이라는 테이블을 생성하여, 
일대다관계를 갖도록 수정하였습니다.

2024-05-09 01:46 UTC, msk226 approved these changes
다대다 관계를 잘 분리 하셨네요! 좋습니다!

2024-05-09 01:48 UTC, msk226 requested changes

2024-05-09 01:48 UTC, msk226 commented on 웨이/week5.sql
> +where userId = 1 and status = true --접속한 사용자 id가 1이라 가정
`status`가 `true, false` 같은 값 보다는 `미션 완료`, `진행중` 등등 과 같이 표현 하는게 어떨까요?

2024-05-09 03:18 UTC, thwldus commented
미션의 상태가 보다 다양할 수 있음을 감안하여, varchar형으로 수정하였습니다.
추가적으로, 여러 사용자에게 할당된 동일한 미션도 각 사용자마다 진행 상태가 다를 수 있으므로 status라는 필드를 별도로 작성했습니다.

2024-05-09 07:40 UTC, msk226 approved these changes
확인했습니다! 고생하셨어요~

2024-05-09 12:16 UTC, hcg0127 approved these changes
수고하셨습니다!

2024-05-10 01:04 UTC, merged